# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: refresh_workflow_version

on:
  push:
    branches: [ test-ci ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install plist
      - name: Refresh Workflow Version
        run:  node ./refresh_workflow_version.js
      - name: Build
          run: |
            git config --global user.email "alan@1991421.cn"
            git config --global user.name "Alan He"
            git add .
            git commit -m 'Update workflow version'
      - name: Deploy GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DEPLOY_4_GITHUB_KEY }}
          branch: test-ci
